In [0]:
# Change directory to VSCode workspace root so that relative path loads work correctly. Turn this addition off with the DataSciece.changeDirOnImportExport setting
import os
try:
	os.chdir(os.path.join(os.getcwd(), '..'))
	print(os.getcwd())
except:
	pass

In [1]:
# file import
import pandas as pd  
friday = pd.read_csv('~/pytong/data-cleaning/BlackFriday.csv')

In [2]:
# looking at the data
# table shape
print(friday.shape)

(537577, 12)

In [3]:
# first 10 rows
print(friday.head(10))

   User_ID Product_ID Gender    Age  Occupation City_Category  \
0  1000001  P00069042      F   0-17          10             A
1  1000001  P00248942      F   0-17          10             A
2  1000001  P00087842      F   0-17          10             A
3  1000001  P00085442      F   0-17          10             A
4  1000002  P00285442      M    55+          16             C
5  1000003  P00193542      M  26-35          15             A
6  1000004  P00184942      M  46-50           7             B
7  1000004  P00346142      M  46-50           7             B
8  1000004   P0097242      M  46-50           7             B
9  1000005  P00274942      M  26-35          20             A

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3
1                          2               0                   1
2                          2               0                  12
3                          2               0                  12
4                         4+               0                   8
5                          3               0                   1
6                          2               1                   1
7                          2               1                   1
8                          2               1                   1
9                          1               1                   8

   Product_Category_2  Product_Category_3  Purchase
0                 NaN                 NaN      8370
1                 6.0                14.0     15200
2                 NaN                 NaN      1422
3                14.0                 NaN      1057
4                 NaN                 NaN      7969
5                 2.0                 NaN     15227
6                 8.0                17.0     19215
7                15.0                 NaN     15854
8                16.0                 NaN     15686
9                 NaN                 NaN      7871

In [4]:
# let's look at column types
print(friday.dtypes)

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
dtype: object

In [5]:
# learn some more about purchase price
purch = friday["Purchase"]
print(purch.describe())

count    537577.000000
mean       9333.859853
std        4981.022133
min         185.000000
25%        5866.000000
50%        8062.000000
75%       12073.000000
max       23961.000000
Name: Purchase, dtype: float64

In [7]:
# take a look at row with purchase with highest price
highest_purch = friday.loc[friday["Purchase"]==23961]
print(highest_purch)

        User_ID Product_ID Gender    Age  Occupation City_Category  \
87440   1001474  P00052842      M  26-35           4             A
93016   1002272  P00052842      M  26-35           0             C
370891  1003160  P00052842      M  26-35          17             C

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
87440                           2               1                  10
93016                           1               0                  10
370891                          3               0                  10

        Product_Category_2  Product_Category_3  Purchase
87440                 15.0                 NaN     23961
93016                 15.0                 NaN     23961
370891                15.0                 NaN     23961

In [8]:
# exploring Age column
age = friday["Age"]
print(age.value_counts())

26-35    214690
36-45    107499
18-25     97634
46-50     44526
51-55     37618
55+       20903
0-17      14707
Name: Age, dtype: int64

In [11]:
# take a look at the same column but with gender split
# females
age_female = friday.loc[friday["Gender"]=="F","Age"]
print(age_female.value_counts())

26-35    49348
36-45    26420
18-25    24057
46-50    12856
51-55     9634
0-17      4953
55+       4929
Name: Age, dtype: int64

In [12]:
#males
age_male = friday.loc[friday["Gender"]=="M","Age"]
print(age_male.value_counts())

26-35    165342
36-45     81079
18-25     73577
46-50     31670
51-55     27984
55+       15974
0-17       9754
Name: Age, dtype: int64

In [18]:
# it seems that males had made 3 times more purchases than females

In [19]:
# number of purchases made by females
print(age_female.shape)

(132197,)

In [20]:
# number of purchases made by males
print(age_male.shape)

(405380,)

In [22]:
# checking percentage of women
print(age_female.shape[0]/(age_female.shape[0]+age_male.shape[0])*100)

0

In [27]:
# checking percentage of women
tot_fem = float(age_female.shape[0])
print(tot_fem)
tot_mal = float(age_male.shape[0])
print(tot_mal)
tot_gen = tot_fem + tot_mal
fem_perc = tot_fem/tot_gen*100
print(fem_perc)

132197.0
405380.0
24.5912678556

In [28]:
# checking percentage of men
mal_perc = tot_mal/tot_gen*100
print(mal_perc)

75.4087321444

In [29]:
# it looks like 3 times more man than women made purchases during black friday